### ISSUE TITLE
Toolchain Update

### ISSUE THREAD

**Issue by rshchekotov** [GuptaGenomicsLab/cli#1]
After looking through the codebase, I noticed that you're still stuck on an out-of-date toolchain - "Python" was its name, wasn't it?

So, after a bit of research I came across this rather modern toolchain, which is **made for** scientific computing: [Julia](https://julialang.org/).
It supports all currently required capabilities:
- [CLI](https://juliapackages.com/p/cli)
- [HTTP Requests](https://juliapackages.com/p/http)
- Data Parsing / Writing: [CSV](https://juliapackages.com/p/csv), [JSON](https://juliapackages.com/p/json)
- External "[OS Commands](https://docs.julialang.org/en/v1/manual/running-external-programs/)"
- [Parallel Computing](https://docs.julialang.org/en/v1/manual/parallel-computing/)

So, what else can I say: upgrade so you can reduce the technical debt in the future.
If you need a PR, which showcases how to use this new-to-you language, I can gladly create one.

Cheers,
~Doom, PhD (in Refactoring & Variable Naming)

**Comment by dkantereivin** [comment]
Thanks for the suggestion. We strongly consider Julia and is a tool that's been used internally for a private project and will likely be used in my next project.

For this project, we've chosen Python as the tool is mostly used internally. Python makes this the simplest given that existing computers have Python installed and lab members are familiar with Python.

Moreover, Julia is arguably not the best choice for a CLI tool such as this as it has a very slow startup time. While Julia has great performance, this applies to performance intensive tasks, which this command line tool is generally not responsible for. Instead, having a simple CLI and GUI which opens quickly is much more important.
